name: Build and Release Zeno

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun environment
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the application
      - name: Build Zeno
        run: |
          bun build src/index.ts --outdir dist --minify --compile

      # Package the binary
      - name: Package binary
        run: |
          tar -czvf zeno-${{ matrix.os }}-${{ matrix.arch }}.tar.gz dist/
        shell: bash

      # Upload artifact for this matrix
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zeno-${{ matrix.os }}-${{ matrix.arch }}
          path: zeno-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download artifacts from the build job
      - name: Download artifacts
        uses: actions/download-artifact@v3

      # Upload artifacts to GitHub Releases
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            zeno-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
